// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN7IIfLZn7slMFdyyhCrbFEkt5NMyGN-k',
    appId: '1:732847095789:web:8901e8500da47f89f6b1e4',
    messagingSenderId: '732847095789',
    projectId: 'vapaat-5ec50',
    authDomain: 'vapaat-5ec50.firebaseapp.com',
    storageBucket: 'vapaat-5ec50.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx3AgPBD-lXxFZkpP5PIxqiHIyhcPIttc',
    appId: '1:732847095789:android:ba73159114a2fab2f6b1e4',
    messagingSenderId: '732847095789',
    projectId: 'vapaat-5ec50',
    storageBucket: 'vapaat-5ec50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeeklpqIwPzNDeYrrXGbtaRQsO40x3JZo',
    appId: '1:732847095789:ios:a310334eac5a0502f6b1e4',
    messagingSenderId: '732847095789',
    projectId: 'vapaat-5ec50',
    storageBucket: 'vapaat-5ec50.appspot.com',
    iosClientId: '732847095789-8m534hit7q0p3mnfaeon6skg8abt9q0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeeklpqIwPzNDeYrrXGbtaRQsO40x3JZo',
    appId: '1:732847095789:ios:a310334eac5a0502f6b1e4',
    messagingSenderId: '732847095789',
    projectId: 'vapaat-5ec50',
    storageBucket: 'vapaat-5ec50.appspot.com',
    iosClientId: '732847095789-8m534hit7q0p3mnfaeon6skg8abt9q0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
